### ISSUE TITLE
Data publication V6

### ISSUE THREAD

**Issue by sbashevkin** [InteragencyEcologicalProgram/discretewq#33]
Preparing a new data publication

TODO

- [x] Check R/data.R for missing variables and add all missing variables
- [x] Check NCRO sign variables (Dave)
- [x] Add metadata for new variables (mostly "_Sign" ones) to publication/metadata_templates/attributes_Delta_Integrated_WQ.txt. All new variables have been added but they need metadata. (Sam)
- [x] Check whether all of the data sources in the data.R and README documentation are up to date (Sam)
- [x] Update publication/metadata_templates/provenance.txt and methods.docx with correct versions of each dataset and the NCRO data citation (Sam)
- [x] Add NCRO survey to publication/data_objects/Delta_Integrated_WQ_metadata.csv and fill in relevant info (Start year, season, frequency, data source, and sampling depths) (Dave)
- [x] Update publication/metadata_templates/methods.docx with any important updates, including new survey (NCRO) and citation to latest `discretewq` version (which should be 2.4). (Dave)
- [x] Have Liz take a look at publication/metadata_templates/methods.docx to add any relevant info about the USGS_CAWSC survey particularly in the Chlorophyll and Nutrients sections
- [x]  Update contact info in publication/metadata_templates/personnel.txt (Sam)
- [x] Tag `discretewq` to version 2.4, release on github, and edit zenodo publication, edit zenodo citation on README and publication/metadata_templates/methods.docx
- [x] Upload Delta_Integrated_WQ.csv and Delta_Integrated_WQ_metadata.csv to box.com or dropbox.com or similar and supply their public URLs to `make_eml` function
- [x] Create final EML file
- [x] Publish to [sandbox EDI](https://portal-s.edirepository.org/nis/home.jsp) and review
- [x] Publish to real EDI

**Comment by mountaindboz** [comment]
Data has been published to EDI: https://portal.edirepository.org/nis/mapbrowse?packageid=edi.731.7
