### ISSUE TITLE
EMP 2022 update - "Sign" variables

### ISSUE THREAD

**Issue by mountaindboz** [InteragencyEcologicalProgram/discretewq#40]
FYI @sbashevkin and @rosehartman (since it looks like you recently downloaded data from `discretewq`)

After the 2022 update for the EMP data, only data collected in 2022 has "<" values in the "_Sign" variables. Earlier versions of the EMP data have "<" values in the "_Sign" variables for most of the years. I traced this issue back to the most recent EMP EDI data publication, [version 458.8](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=458&revision=8). In the most recent EDI publication, all of the values prior to 2022 that used to have "<" in a "_Sign" variable are now "=". I contacted @seperry83 about this and they are working on it.

**Comment by sbashevkin** [comment]
Thanks Dave and Sarah! We could add a test to automatically check for this in the future if it would be helpful?

**Comment by seperry83** [comment]
Agreed; I'm also planning on adding more tests on my end (for the initial EDI publication).

Also, I'll have the updated dataset pushed by the end of today.

**Comment by seperry83** [comment]
The data has been updated and submitted to EMP's EDI; once that's corrected, I'll update it here.

**Comment by mountaindboz** [comment]
Great, thanks Sarah!

**Comment by mountaindboz** [comment]
@seperry83 - It looks like the data has been updated in EDI now. Would you be able to update the EMP data in `discretewq` within the next few days? Thanks!

**Comment by sbashevkin** [comment]
I'm guessing that is what Sarah already did with PR https://github.com/InteragencyEcologicalProgram/discretewq/pull/41?

**Comment by mountaindboz** [comment]
Ah, thanks for pointing that out @sbashevkin! I didn't see that PR when I sent this message. I'll merge PR #41 into main and update the data source links for EMP to the EDI publication 458.9. @seperry83 - I think we're good to go now. Thanks for taking care of this!
